services:
  anyconnect-vpn:
    image: thebv/vpn:latest
    restart: no
    container_name: anyconnect-vpn
    hostname: anyconnect-vpn
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 2222:22
    env_file: .env
    command: openconnect $VPN_URL --allow-insecure-crypto --user=$VPN_USERNAME --form-entry main:password=$VPN_PASSWORD
    volumes:
      - ./authorized_keys:/root/.ssh/authorized_keys